# Generated by Django 6.1.1 on 2026-09-29 23:28

import apps.accounts.models
import apps.core.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=64)),
                ('role', models.CharField(choices=[('player', 'Player'), ('support', 'Support agent'), ('trader', 'Trader'), ('finance', 'Finance'), ('risk_analyst', 'Risk analyst'), ('admin', 'Administrator')], default='player', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('self_excluded', 'Self-excluded'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthChallenge',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('chain', models.CharField(choices=[('evm', 'EVM (Ethereum, BSC, Polygon, ...)'), ('ton', 'TON')], max_length=10)),
                ('purpose', models.CharField(choices=[('login', 'Login / register'), ('link_wallet', 'Link wallet to existing account')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=128)),
                ('message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedWallet',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chain', models.CharField(choices=[('evm', 'EVM (Ethereum, BSC, Polygon, ...)'), ('ton', 'TON')], max_length=10)),
                ('address', models.CharField(max_length=128)),
                ('public_key', models.CharField(blank=True, max_length=64)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_staff', True), ('role', 'player'), _negated=True), name='accounts_user_player_not_staff'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('is_superuser', False), ('role', 'admin'), _connector='OR'), name='accounts_user_superuser_is_admin'),
        ),
        migrations.AddConstraint(
            model_name='linkedwallet',
            constraint=models.UniqueConstraint(fields=('chain', 'address'), name='accounts_linkedwallet_unique_chain_address'),
        ),
    ]
