# Generated by Django 6.1.1 on 2026-09-29 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('market_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('suspended', 'Suspended'), ('settled', 'Settled')], db_index=True, default='open', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('usdt', 'USDT'), ('ton', 'TON'), ('stars', 'Telegram Stars'), ('bonus', 'Bonus credits')], max_length=10)),
                ('bet_type', models.CharField(choices=[('single', 'Single'), ('combo', 'Combo')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('void', 'Void')], db_index=True, default='pending', max_length=16)),
                ('stake_amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('total_odds', models.DecimalField(decimal_places=4, max_digits=12)),
                ('potential_payout', models.DecimalField(decimal_places=8, max_digits=28)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reservation_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.ledgertransaction')),
                ('settlement_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wallet.ledgertransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('current_odds', models.DecimalField(decimal_places=4, max_digits=12)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.market')),
            ],
        ),
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'start_time'], name='betting_spo_status_02ff79_idx')],
            },
        ),
        migrations.AddField(
            model_name='market',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='betting.sportevent'),
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_odds', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('void', 'Void')], default='pending', max_length=16)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.bet')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bet_selections', to='betting.selection')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bet_selections', to='betting.sportevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['user', 'status', '-placed_at'], name='betting_bet_user_id_084318_idx'),
        ),
        migrations.AddConstraint(
            model_name='selection',
            constraint=models.CheckConstraint(condition=models.Q(('current_odds__gte', 1)), name='betting_selection_odds_gte_1'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['event', 'status'], name='betting_mar_event_i_7025d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='betselection',
            constraint=models.UniqueConstraint(fields=('bet', 'selection'), name='betting_betselection_unique_bet_selection'),
        ),
        migrations.AddConstraint(
            model_name='betselection',
            constraint=models.CheckConstraint(condition=models.Q(('locked_odds__gte', 1)), name='betting_betselection_odds_gte_1'),
        ),
    ]
