# Generated by Django 6.1.1 on 2026-09-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('void', 'Void')], default='pending', max_length=10),
        ),
    ]
