# Generated by Django 6.1.1 on 2026-09-29 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('player_available', 'Player available balance'), ('player_locked', 'Player locked balance'), ('system_deposits', 'Deposits clearing'), ('system_withdrawals', 'Withdrawals clearing'), ('system_house_revenue', 'House revenue'), ('system_escrow', 'Escrow (reserved for future multi-party markets)'), ('system_fees', 'Platform fees'), ('telegram_services_escrow', 'Telegram services escrow'), ('system_bonus_pool', 'Bonus credit pool')], max_length=32)),
                ('currency', models.CharField(choices=[('usdt', 'USDT'), ('ton', 'TON'), ('stars', 'Telegram Stars'), ('bonus', 'Bonus credits')], max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bet_reservation', 'Bet reservation'), ('bet_payout', 'Bet payout'), ('bet_cancel_refund', 'Bet cancel / refund'), ('purchase_tg_stars', 'Telegram Stars purchase'), ('purchase_tg_premium', 'Telegram Premium purchase'), ('purchase_nft', 'NFT purchase'), ('bonus_grant', 'Bonus grant')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('currency', models.CharField(choices=[('usdt', 'USDT'), ('ton', 'TON'), ('stars', 'Telegram Stars'), ('bonus', 'Bonus credits')], max_length=10)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['transaction_type', 'status'], name='wallet_ledg_transac_e0b2ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.ledgeraccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wallet.ledgertransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=apps.core.models.generate_uuid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('usdt', 'USDT'), ('ton', 'TON'), ('stars', 'Telegram Stars'), ('bonus', 'Bonus credits')], max_length=10)),
                ('available_balance', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('locked_balance', models.DecimalField(decimal_places=8, default=0, max_digits=28)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('account_type', 'currency'), name='wallet_ledgeraccount_unique_system'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'account_type', 'currency'), name='wallet_ledgeraccount_unique_player'),
        ),
        migrations.AddConstraint(
            model_name='ledgeraccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_type__in', frozenset(['player_available', 'player_locked'])), ('user__isnull', False)), models.Q(models.Q(('account_type__in', frozenset(['player_available', 'player_locked'])), _negated=True), ('user__isnull', True)), _connector='OR'), name='wallet_ledgeraccount_user_matches_type'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='wallet_ledg_account_a28aa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='wallet_ledgerentry_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'currency'), name='wallet_wallet_unique_user_currency'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='wallet_wallet_available_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('locked_balance__gte', 0)), name='wallet_wallet_locked_gte_0'),
        ),
    ]
